### ISSUE TITLE
How Do You Use This?

### ISSUE THREAD

**Issue by ricebandit** [renanveroneze/brackets-open-terminal#1]
Can you please provide information on how to use this? I installed this extension to my copy of Brackets, but I don't see any shortcut buttons, nor do I see any option in any of the menus...?

**Comment by renanveroneze** [comment]
Hello, this extension works by adding an item in the context menu!
Watch the video I made for you, another important thing, I haven't tested this extension on Windows!

http://youtu.be/OH2CLmF4b_Q

Any questions, tell me!

Thanks

**Comment by ricebandit** [comment]
This is perfect-- thanks for creating that video so quickly! 

May I suggest you add it to your Open Terminal github page? In the Brackets Extensions listings, the "More Info..." link pulls up this page:

https://github.com/renanveroneze/brackets-open-terminal

From the user-standpoint, if there's no information on how to use it, it's possible that they will just uninstall it after not figuring it out or will bother you with the same question...

Awesome, though! :)

**Comment by renanveroneze** [comment]
@ricebandit Thanks for the tip! I've updated the readme
